version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: bank-db
    env_file:
      - .env
    environment:
      POSTGRES_DB: bank_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: